<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>InputUsername</description>
   <name>password</name>
   <tag></tag>
   <elementGuidId>7513bcf4-12df-40e8-b920-bb6ddf706638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='modalLoginPassword']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
