<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>UserNotFound</description>
   <name>ToastNotifErrorUser</name>
   <tag></tag>
   <elementGuidId>c0a4fe9c-5040-4cd0-93f0-3671203b3f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='alert']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
