<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>InputUsername</description>
   <name>username</name>
   <tag></tag>
   <elementGuidId>18ec818a-d8ac-4543-a34d-16beb18ffa3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='modalLoginUsername']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
